# apiVersion: v1
# kind: Pod
# metadata:
#   name: redis
# spec:
#   containers:
#   - name: redis
#     image: redis:5.0.4
#     command:
#       - redis-server
#       - "/redis-master/redis.conf"
#     env:
#     - name: MASTER
#       value: "true"
#     ports:
#     - containerPort: 6379
#     resources:
#       limits:
#         cpu: "0.1"
#     volumeMounts:
#     - mountPath: /redis-master-data
#       name: data
#     - mountPath: /redis-master
#       name: config
#   volumes:
#     - name: data
#       emptyDir: {}
#     - name: config
#       configMap:
#         name: example-redis-config
#         items:
#         - key: redis-config
#           path: redis.conf

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: redis
# spec:
#   selector:
#     matchLabels:
#       app: rredis
#   template:
#     metadata:
#       labels:
#         app: redis
#     spec:
#       containers:
#       - name: redis
#         image: redis:alpine
#         ports:
#         - containerPort: 6379
#         readinessProbe:
#           periodSeconds: 5
#           tcpSocket:
#             port: 6379
#         livenessProbe:
#           periodSeconds: 5
#           tcpSocket:
#             port: 6379
#         volumeMounts:
#         - mountPath: /data
#           name: redis-data
#         resources:
#           limits:
#             memory: 256Mi
#             cpu: 125m
#           requests:
#             cpu: 70m
#             memory: 200Mi
#       volumes:
#       - name: redis-data
#         emptyDir: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis
# spec:
#   type: ClusterIP
#   selector:
#     app: redis
#   ports:
#   - name: redis
#     port: 6379
#     targetPort: 6379

# ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.4
        # env:
        # - name: REDISHOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: redishost
        #       key: REDISHOST
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379