apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.4
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis_test
  labels:
    app: redis_test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis_test
    spec:
      containers:
      - name: redis_test
        image: redis:5.0.4
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis_test
spec:
  type: ClusterIP
  selector:
    app: redis_test
  ports:
  - name: redis_test
    port: 6379
    targetPort: 6379