apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-client
  labels:
    app: redis-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-client
    spec:
      containers:
      - name: redis-client
        image: "tiancanyu/redis-client:v1"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redis-client
spec:
  type: LoadBalancer
  selector:
    app: redis-client
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

